// <auto-generated />
using System;
using DesafioTotvsPDV.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioTotvsPDV.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20181208213806_CriacaoInicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioTotvsPDV.Domain.Entidades.ItemTrocoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdPagamento");

                    b.Property<decimal>("ValorObjetoTroco");

                    b.HasKey("Id");

                    b.HasIndex("IdPagamento");

                    b.ToTable("ItemTrocoPagamento");
                });

            modelBuilder.Entity("DesafioTotvsPDV.Domain.Entidades.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataTransacao");

                    b.Property<decimal>("ValorPago");

                    b.Property<decimal>("ValorTroco");

                    b.Property<decimal>("ValorVenda");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("DesafioTotvsPDV.Domain.Entidades.ItemTrocoPagamento", b =>
                {
                    b.HasOne("DesafioTotvsPDV.Domain.Entidades.Pagamento", "Pagamento")
                        .WithMany("ItensTroco")
                        .HasForeignKey("IdPagamento")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
